"""add inventory and professions

Revision ID: 7914f7355765
Revises: fc7bd44d6e3c
Create Date: 2025-11-26 22:21:21.767857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7914f7355765'
down_revision: Union[str, Sequence[str], None] = 'fc7bd44d6e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_professions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('profession_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_professions_character_id'), 'character_professions', ['character_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_character_id'), 'inventory', ['character_id'], unique=False)
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=True)
    op.create_index(op.f('ix_equipped_items_character_id'), 'equipped_items', ['character_id'], unique=False)
    op.create_index(op.f('ix_equipped_items_item_instance_id'), 'equipped_items', ['item_instance_id'], unique=False)
    op.create_index(op.f('ix_item_instances_owner_id'), 'item_instances', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_instances_owner_id'), table_name='item_instances')
    op.drop_index(op.f('ix_equipped_items_item_instance_id'), table_name='equipped_items')
    op.drop_index(op.f('ix_equipped_items_character_id'), table_name='equipped_items')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_index(op.f('ix_inventory_character_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_character_professions_character_id'), table_name='character_professions')
    op.drop_table('character_professions')
    # ### end Alembic commands ###
