"""Init

Revision ID: fc7bd44d6e3c
Revises: 
Create Date: 2025-11-26 22:08:16.391877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7bd44d6e3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('item_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=30), nullable=False),
    sa.Column('rolled_stats', sa.String(), nullable=False),
    sa.Column('is_listed', sa.Boolean(), nullable=False),
    sa.Column('list_price', sa.Integer(), nullable=False),
    sa.Column('affixes', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipped_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=30), nullable=False),
    sa.Column('item_instance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['item_instance_id'], ['item_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipped_items')
    op.drop_table('item_instances')
    op.drop_table('characters')
    # ### end Alembic commands ###
